# Phase-1 statistical-tests catalog.
#
# Only columns I'm confident on are filled in; the rest are intentionally blank
# for human review. Re-running seeds is safe: existing tests are not modified
# (so admin edits in the UI won't be clobbered), and only new tests are added.
#
# Skipped from this seed (add later as needed):
#   - Kaplan–Meier (estimator, not a hypothesis test)
#   - Dimension Reduction / Latent Structure (PCA, EFA, CFA, IRT, Rasch)
#   - Classification / Clustering (LDA, QDA, K-Means, Hierarchical, DBSCAN)
#   - Agreement / Reliability (Kappas, ICC, Bland–Altman, Cronbach's)
#   - Robust / Resampling / Exact (Bootstrap, Permutation, Monte Carlo, Exact Logistic)
#   - All Bayesian variants

STATISTICAL_TESTS_SEED = [
  # =======================================================================
  # Group Comparison — parametric
  # =======================================================================
  {
    name: 'One-Sample t-test',
    aliases: ['Single-sample t-test'],
    primary_variable_1_type: 'Continuous',
    primary_variable_2_type: 'None / Not Applicable',
    number_of_dependent_variables: 'One',
    number_of_predictors: 'None / Not Applicable',
    number_of_groups_conditions: 'One',
    sample_relationship: 'None / Not Applicable',
    repeated_observations_present: 'No',
    number_of_timepoints: 'One',
    time_matters_to_analysis: 'No',
    censoring_present: 'Not Supported',
    latent_construct_interest: 'No',
    dimension_reduction_goal: 'No',
    analysis_scope: 'Unadjusted / Bivariate',
    primary_output_desired: ['Group Difference'],
    post_hoc_comparisons_needed: 'No',
  },
  {
    name: 'Independent Samples t-test',
    aliases: ['Two-sample t-test', "Student's t-test", 'Unpaired t-test'],
    goal: ['Compare Groups'],
    variable_relationship_structure: 'DV–IV Directional',
    primary_variable_1_type: 'Continuous',
    primary_variable_2_type: 'Binary',
    number_of_dependent_variables: 'One',
    number_of_predictors: 'One',
    number_of_groups_conditions: 'Two',
    sample_relationship: 'Independent',
    repeated_observations_present: 'No',
    number_of_timepoints: 'One',
    time_matters_to_analysis: 'No',
    parametric_assumptions_reasonably_met: 'Yes',
    outcome_approximately_normal: 'Yes',
    equal_variances_assumed: 'Yes',
    censoring_present: 'Not Supported',
    latent_construct_interest: 'No',
    dimension_reduction_goal: 'No',
    analysis_scope: 'Unadjusted / Bivariate',
    primary_output_desired: ['Group Difference'],
    post_hoc_comparisons_needed: 'No',
  },
  {
    name: "Welch's t-test",
    aliases: ['Welch t-test', 'Welch–Satterthwaite t-test', 'Unequal variances t-test'],
    goal: ['Compare Groups'],
    variable_relationship_structure: 'DV–IV Directional',
    primary_variable_1_type: 'Continuous',
    primary_variable_2_type: 'Binary',
    number_of_dependent_variables: 'One',
    number_of_predictors: 'One',
    number_of_groups_conditions: 'Two',
    sample_relationship: 'Independent',
    repeated_observations_present: 'No',
    number_of_timepoints: 'One',
    time_matters_to_analysis: 'No',
    parametric_assumptions_reasonably_met: 'Yes',
    outcome_approximately_normal: 'Yes',
    equal_variances_assumed: 'No',
    censoring_present: 'Not Supported',
    latent_construct_interest: 'No',
    dimension_reduction_goal: 'No',
    analysis_scope: 'Unadjusted / Bivariate',
    primary_output_desired: ['Group Difference'],
    post_hoc_comparisons_needed: 'No',
  },
  {
    name: 'Paired Samples t-test',
    aliases: ['Dependent t-test', 'Within-subjects t-test', 'Matched-pairs t-test'],
    goal: ['Compare Groups'],
    variable_relationship_structure: 'DV–IV Directional',
    primary_variable_1_type: 'Continuous',
    primary_variable_2_type: 'Binary',
    number_of_dependent_variables: 'One',
    number_of_predictors: 'One',
    number_of_groups_conditions: 'Two',
    sample_relationship: 'Paired / Matched',
    repeated_observations_present: 'Yes',
    number_of_timepoints: 'Two',
    parametric_assumptions_reasonably_met: 'Yes',
    outcome_approximately_normal: 'Yes',
    censoring_present: 'Not Supported',
    latent_construct_interest: 'No',
    dimension_reduction_goal: 'No',
    analysis_scope: 'Unadjusted / Bivariate',
    primary_output_desired: ['Group Difference'],
    post_hoc_comparisons_needed: 'No',
  },
  {
    name: 'One-Way ANOVA',
    aliases: ['One-Factor ANOVA'],
    goal: ['Compare Groups'],
    variable_relationship_structure: 'DV–IV Directional',
    primary_variable_1_type: 'Continuous',
    primary_variable_2_type: 'Nominal Categorical',
    number_of_dependent_variables: 'One',
    number_of_predictors: 'One',
    number_of_groups_conditions: 'Three or More',
    sample_relationship: 'Independent',
    repeated_observations_present: 'No',
    number_of_timepoints: 'One',
    time_matters_to_analysis: 'No',
    parametric_assumptions_reasonably_met: 'Yes',
    outcome_approximately_normal: 'Yes',
    equal_variances_assumed: 'Yes',
    censoring_present: 'Not Supported',
    latent_construct_interest: 'No',
    dimension_reduction_goal: 'No',
    analysis_scope: 'Unadjusted / Bivariate',
    primary_output_desired: ['Group Difference'],
    post_hoc_comparisons_needed: 'Yes',
  },
  {
    name: 'Two-Way / Factorial ANOVA',
    aliases: ['Factorial ANOVA', 'Two-Factor ANOVA'],
    goal: ['Compare Groups'],
    variable_relationship_structure: 'DV–IV Directional',
    primary_variable_1_type: 'Continuous',
    primary_variable_2_type: 'Nominal Categorical',
    number_of_dependent_variables: 'One',
    number_of_predictors: 'Multiple',
    number_of_groups_conditions: 'Three or More',
    sample_relationship: 'Independent',
    repeated_observations_present: 'No',
    number_of_timepoints: 'One',
    time_matters_to_analysis: 'No',
    parametric_assumptions_reasonably_met: 'Yes',
    outcome_approximately_normal: 'Yes',
    equal_variances_assumed: 'Yes',
    moderation: 'Supported',
    censoring_present: 'Not Supported',
    latent_construct_interest: 'No',
    dimension_reduction_goal: 'No',
    analysis_scope: 'Adjusted / Multivariable',
    primary_output_desired: ['Group Difference'],
    post_hoc_comparisons_needed: 'Yes',
  },
  {
    name: 'Repeated Measures ANOVA',
    aliases: ['RM-ANOVA', 'Within-Subjects ANOVA'],
    goal: ['Compare Groups'],
    variable_relationship_structure: 'DV–IV Directional',
    primary_variable_1_type: 'Continuous',
    primary_variable_2_type: 'Nominal Categorical',
    number_of_dependent_variables: 'One',
    number_of_predictors: 'One',
    number_of_groups_conditions: 'Three or More',
    sample_relationship: 'Repeated Measures',
    repeated_observations_present: 'Yes',
    number_of_timepoints: 'Three or More',
    parametric_assumptions_reasonably_met: 'Yes',
    outcome_approximately_normal: 'Yes',
    censoring_present: 'Not Supported',
    latent_construct_interest: 'No',
    dimension_reduction_goal: 'No',
    analysis_scope: 'Unadjusted / Bivariate',
    primary_output_desired: ['Group Difference'],
    post_hoc_comparisons_needed: 'Yes',
  },
  {
    name: 'Mixed ANOVA',
    aliases: ['Split-Plot ANOVA', 'Mixed-Design ANOVA'],
    goal: ['Compare Groups'],
    variable_relationship_structure: 'DV–IV Directional',
    primary_variable_1_type: 'Continuous',
    primary_variable_2_type: 'Nominal Categorical',
    number_of_dependent_variables: 'One',
    number_of_predictors: 'Multiple',
    number_of_groups_conditions: 'Three or More',
    sample_relationship: 'Mixed',
    repeated_observations_present: 'Yes',
    number_of_timepoints: 'Three or More',
    parametric_assumptions_reasonably_met: 'Yes',
    outcome_approximately_normal: 'Yes',
    moderation: 'Supported',
    censoring_present: 'Not Supported',
    latent_construct_interest: 'No',
    dimension_reduction_goal: 'No',
    analysis_scope: 'Adjusted / Multivariable',
    primary_output_desired: ['Group Difference'],
    post_hoc_comparisons_needed: 'Yes',
  },
  {
    name: 'ANCOVA',
    aliases: ['Analysis of Covariance'],
    goal: ['Compare Groups'],
    variable_relationship_structure: 'DV–IV Directional',
    primary_variable_1_type: 'Continuous',
    primary_variable_2_type: 'Mixed',
    number_of_dependent_variables: 'One',
    number_of_predictors: 'Multiple',
    sample_relationship: 'Independent',
    repeated_observations_present: 'No',
    number_of_timepoints: 'One',
    time_matters_to_analysis: 'No',
    covariates_included: 'Required',
    parametric_assumptions_reasonably_met: 'Yes',
    outcome_approximately_normal: 'Yes',
    equal_variances_assumed: 'Yes',
    censoring_present: 'Not Supported',
    latent_construct_interest: 'No',
    dimension_reduction_goal: 'No',
    analysis_scope: 'Adjusted / Multivariable',
    primary_output_desired: ['Group Difference'],
    post_hoc_comparisons_needed: 'Yes',
  },
  {
    name: 'MANOVA',
    aliases: ['Multivariate Analysis of Variance'],
    goal: ['Compare Groups'],
    variable_relationship_structure: 'DV–IV Directional',
    primary_variable_1_type: 'Continuous',
    primary_variable_2_type: 'Nominal Categorical',
    number_of_dependent_variables: 'Multiple',
    sample_relationship: 'Independent',
    repeated_observations_present: 'No',
    number_of_timepoints: 'One',
    time_matters_to_analysis: 'No',
    parametric_assumptions_reasonably_met: 'Yes',
    outcome_approximately_normal: 'Yes',
    censoring_present: 'Not Supported',
    latent_construct_interest: 'No',
    dimension_reduction_goal: 'No',
    analysis_scope: 'Multivariate',
    primary_output_desired: ['Group Difference'],
    post_hoc_comparisons_needed: 'Yes',
  },
  {
    name: 'MANCOVA',
    aliases: ['Multivariate Analysis of Covariance'],
    goal: ['Compare Groups'],
    variable_relationship_structure: 'DV–IV Directional',
    primary_variable_1_type: 'Continuous',
    primary_variable_2_type: 'Mixed',
    number_of_dependent_variables: 'Multiple',
    number_of_predictors: 'Multiple',
    sample_relationship: 'Independent',
    repeated_observations_present: 'No',
    number_of_timepoints: 'One',
    time_matters_to_analysis: 'No',
    covariates_included: 'Required',
    parametric_assumptions_reasonably_met: 'Yes',
    outcome_approximately_normal: 'Yes',
    censoring_present: 'Not Supported',
    latent_construct_interest: 'No',
    dimension_reduction_goal: 'No',
    analysis_scope: 'Multivariate',
    primary_output_desired: ['Group Difference'],
    post_hoc_comparisons_needed: 'Yes',
  },

  # =======================================================================
  # Nonparametric Group Comparisons
  # =======================================================================
  {
    name: 'Mann–Whitney U Test',
    aliases: ['Wilcoxon Rank-Sum Test', 'Mann–Whitney–Wilcoxon Test', 'U-Test'],
    goal: ['Compare Groups'],
    variable_relationship_structure: 'DV–IV Directional',
    primary_variable_2_type: 'Binary',
    number_of_dependent_variables: 'One',
    number_of_predictors: 'One',
    number_of_groups_conditions: 'Two',
    sample_relationship: 'Independent',
    repeated_observations_present: 'No',
    number_of_timepoints: 'One',
    time_matters_to_analysis: 'No',
    parametric_assumptions_reasonably_met: 'No',
    outcome_approximately_normal: 'No',
    censoring_present: 'Not Supported',
    latent_construct_interest: 'No',
    dimension_reduction_goal: 'No',
    analysis_scope: 'Unadjusted / Bivariate',
    primary_output_desired: ['Group Difference'],
    post_hoc_comparisons_needed: 'No',
  },
  {
    name: 'Wilcoxon Signed-Rank Test',
    aliases: ['Wilcoxon T-Test', 'Signed-Rank Test'],
    goal: ['Compare Groups'],
    variable_relationship_structure: 'DV–IV Directional',
    primary_variable_2_type: 'Binary',
    number_of_dependent_variables: 'One',
    number_of_predictors: 'One',
    number_of_groups_conditions: 'Two',
    sample_relationship: 'Paired / Matched',
    repeated_observations_present: 'Yes',
    number_of_timepoints: 'Two',
    parametric_assumptions_reasonably_met: 'No',
    outcome_approximately_normal: 'No',
    censoring_present: 'Not Supported',
    latent_construct_interest: 'No',
    dimension_reduction_goal: 'No',
    analysis_scope: 'Unadjusted / Bivariate',
    primary_output_desired: ['Group Difference'],
    post_hoc_comparisons_needed: 'No',
  },
  {
    name: 'Kruskal–Wallis Test',
    aliases: ['Kruskal–Wallis H-Test', 'One-Way ANOVA on Ranks'],
    goal: ['Compare Groups'],
    variable_relationship_structure: 'DV–IV Directional',
    primary_variable_2_type: 'Nominal Categorical',
    number_of_dependent_variables: 'One',
    number_of_predictors: 'One',
    number_of_groups_conditions: 'Three or More',
    sample_relationship: 'Independent',
    repeated_observations_present: 'No',
    number_of_timepoints: 'One',
    time_matters_to_analysis: 'No',
    parametric_assumptions_reasonably_met: 'No',
    outcome_approximately_normal: 'No',
    censoring_present: 'Not Supported',
    latent_construct_interest: 'No',
    dimension_reduction_goal: 'No',
    analysis_scope: 'Unadjusted / Bivariate',
    primary_output_desired: ['Group Difference'],
    post_hoc_comparisons_needed: 'Yes',
  },
  {
    name: 'Friedman Test',
    aliases: ['Friedman Two-Way ANOVA'],
    goal: ['Compare Groups'],
    variable_relationship_structure: 'DV–IV Directional',
    primary_variable_2_type: 'Nominal Categorical',
    number_of_dependent_variables: 'One',
    number_of_predictors: 'One',
    number_of_groups_conditions: 'Three or More',
    sample_relationship: 'Repeated Measures',
    repeated_observations_present: 'Yes',
    number_of_timepoints: 'Three or More',
    parametric_assumptions_reasonably_met: 'No',
    outcome_approximately_normal: 'No',
    censoring_present: 'Not Supported',
    latent_construct_interest: 'No',
    dimension_reduction_goal: 'No',
    analysis_scope: 'Unadjusted / Bivariate',
    primary_output_desired: ['Group Difference'],
    post_hoc_comparisons_needed: 'Yes',
  },

  # =======================================================================
  # Association / Correlation
  # =======================================================================
  {
    name: 'Pearson Correlation',
    aliases: ['Pearson r', 'Pearson Product-Moment Correlation'],
    goal: ['Test Association'],
    variable_relationship_structure: 'Symmetric / Correlation',
    primary_variable_1_type: 'Continuous',
    primary_variable_2_type: 'Continuous',
    number_of_dependent_variables: 'One',
    number_of_predictors: 'None / Not Applicable',
    number_of_groups_conditions: 'None / Not Applicable',
    sample_relationship: 'None / Not Applicable',
    repeated_observations_present: 'No',
    number_of_timepoints: 'One',
    time_matters_to_analysis: 'No',
    parametric_assumptions_reasonably_met: 'Yes',
    outcome_approximately_normal: 'Yes',
    censoring_present: 'Not Supported',
    latent_construct_interest: 'No',
    dimension_reduction_goal: 'No',
    analysis_scope: 'Unadjusted / Bivariate',
    primary_output_desired: ['Correlation'],
    post_hoc_comparisons_needed: 'No',
  },
  {
    name: 'Spearman Rank Correlation',
    aliases: ["Spearman's rho", 'Rank Correlation'],
    goal: ['Test Association'],
    variable_relationship_structure: 'Symmetric / Correlation',
    number_of_dependent_variables: 'One',
    number_of_predictors: 'None / Not Applicable',
    number_of_groups_conditions: 'None / Not Applicable',
    sample_relationship: 'None / Not Applicable',
    repeated_observations_present: 'No',
    number_of_timepoints: 'One',
    time_matters_to_analysis: 'No',
    parametric_assumptions_reasonably_met: 'No',
    outcome_approximately_normal: 'No',
    censoring_present: 'Not Supported',
    latent_construct_interest: 'No',
    dimension_reduction_goal: 'No',
    analysis_scope: 'Unadjusted / Bivariate',
    primary_output_desired: ['Correlation'],
    post_hoc_comparisons_needed: 'No',
  },
  {
    name: "Kendall's Tau",
    aliases: ["Kendall's Tau-b", 'Kendall Rank Correlation'],
    goal: ['Test Association'],
    variable_relationship_structure: 'Symmetric / Correlation',
    number_of_dependent_variables: 'One',
    number_of_predictors: 'None / Not Applicable',
    number_of_groups_conditions: 'None / Not Applicable',
    sample_relationship: 'None / Not Applicable',
    repeated_observations_present: 'No',
    number_of_timepoints: 'One',
    time_matters_to_analysis: 'No',
    parametric_assumptions_reasonably_met: 'No',
    outcome_approximately_normal: 'No',
    censoring_present: 'Not Supported',
    latent_construct_interest: 'No',
    dimension_reduction_goal: 'No',
    analysis_scope: 'Unadjusted / Bivariate',
    primary_output_desired: ['Correlation'],
    post_hoc_comparisons_needed: 'No',
  },
  {
    name: 'Partial Correlation',
    aliases: [],
    goal: ['Test Association'],
    variable_relationship_structure: 'Symmetric / Correlation',
    primary_variable_1_type: 'Continuous',
    primary_variable_2_type: 'Continuous',
    number_of_dependent_variables: 'One',
    number_of_predictors: 'None / Not Applicable',
    repeated_observations_present: 'No',
    number_of_timepoints: 'One',
    time_matters_to_analysis: 'No',
    covariates_included: 'Required',
    censoring_present: 'Not Supported',
    latent_construct_interest: 'No',
    dimension_reduction_goal: 'No',
    analysis_scope: 'Adjusted / Multivariable',
    primary_output_desired: ['Correlation'],
    post_hoc_comparisons_needed: 'No',
  },
  {
    name: 'Point-Biserial Correlation',
    aliases: [],
    goal: ['Test Association'],
    variable_relationship_structure: 'Symmetric / Correlation',
    primary_variable_1_type: 'Continuous',
    primary_variable_2_type: 'Binary',
    number_of_dependent_variables: 'One',
    number_of_predictors: 'None / Not Applicable',
    number_of_groups_conditions: 'None / Not Applicable',
    sample_relationship: 'None / Not Applicable',
    repeated_observations_present: 'No',
    number_of_timepoints: 'One',
    time_matters_to_analysis: 'No',
    censoring_present: 'Not Supported',
    latent_construct_interest: 'No',
    dimension_reduction_goal: 'No',
    analysis_scope: 'Unadjusted / Bivariate',
    primary_output_desired: ['Correlation'],
    post_hoc_comparisons_needed: 'No',
  },
  {
    name: 'Phi Coefficient',
    aliases: ['Mean Square Contingency Coefficient'],
    goal: ['Test Association'],
    variable_relationship_structure: 'Symmetric / Correlation',
    primary_variable_1_type: 'Binary',
    primary_variable_2_type: 'Binary',
    number_of_dependent_variables: 'One',
    number_of_predictors: 'None / Not Applicable',
    number_of_groups_conditions: 'None / Not Applicable',
    sample_relationship: 'None / Not Applicable',
    repeated_observations_present: 'No',
    number_of_timepoints: 'One',
    time_matters_to_analysis: 'No',
    censoring_present: 'Not Supported',
    latent_construct_interest: 'No',
    dimension_reduction_goal: 'No',
    analysis_scope: 'Unadjusted / Bivariate',
    primary_output_desired: ['Correlation'],
    post_hoc_comparisons_needed: 'No',
  },
  {
    name: "Cramér's V",
    aliases: ["Cramér's Phi"],
    goal: ['Test Association'],
    variable_relationship_structure: 'Symmetric / Correlation',
    primary_variable_1_type: 'Nominal Categorical',
    primary_variable_2_type: 'Nominal Categorical',
    number_of_dependent_variables: 'One',
    number_of_predictors: 'None / Not Applicable',
    number_of_groups_conditions: 'None / Not Applicable',
    sample_relationship: 'None / Not Applicable',
    repeated_observations_present: 'No',
    number_of_timepoints: 'One',
    time_matters_to_analysis: 'No',
    censoring_present: 'Not Supported',
    latent_construct_interest: 'No',
    dimension_reduction_goal: 'No',
    analysis_scope: 'Unadjusted / Bivariate',
    primary_output_desired: ['Correlation'],
    post_hoc_comparisons_needed: 'No',
  },

  # =======================================================================
  # Categorical / Frequency
  # =======================================================================
  {
    name: 'Chi-Square Test of Independence',
    aliases: ['Pearson Chi-Square Test'],
    goal: ['Test Association'],
    variable_relationship_structure: 'Symmetric / Correlation',
    primary_variable_1_type: 'Nominal Categorical',
    primary_variable_2_type: 'Nominal Categorical',
    number_of_dependent_variables: 'One',
    number_of_predictors: 'None / Not Applicable',
    sample_relationship: 'Independent',
    repeated_observations_present: 'No',
    number_of_timepoints: 'One',
    time_matters_to_analysis: 'No',
    parametric_assumptions_reasonably_met: 'No',
    outcome_approximately_normal: 'Not Applicable',
    censoring_present: 'Not Supported',
    latent_construct_interest: 'No',
    dimension_reduction_goal: 'No',
    analysis_scope: 'Unadjusted / Bivariate',
  },
  {
    name: 'Chi-Square Goodness-of-Fit Test',
    aliases: ["Pearson's Goodness-of-Fit Test"],
    goal: ['Test Frequencies Against Expected Values'],
    primary_variable_1_type: 'Nominal Categorical',
    primary_variable_2_type: 'None / Not Applicable',
    number_of_dependent_variables: 'One',
    number_of_predictors: 'None / Not Applicable',
    number_of_groups_conditions: 'One',
    sample_relationship: 'None / Not Applicable',
    repeated_observations_present: 'No',
    number_of_timepoints: 'One',
    time_matters_to_analysis: 'No',
    parametric_assumptions_reasonably_met: 'No',
    outcome_approximately_normal: 'Not Applicable',
    censoring_present: 'Not Supported',
    latent_construct_interest: 'No',
    dimension_reduction_goal: 'No',
    analysis_scope: 'Unadjusted / Bivariate',
  },
  {
    name: "Fisher's Exact Test",
    aliases: ['Fisher–Irwin Test'],
    goal: ['Test Association'],
    variable_relationship_structure: 'Symmetric / Correlation',
    primary_variable_1_type: 'Binary',
    primary_variable_2_type: 'Binary',
    number_of_dependent_variables: 'One',
    sample_relationship: 'Independent',
    repeated_observations_present: 'No',
    number_of_timepoints: 'One',
    time_matters_to_analysis: 'No',
    parametric_assumptions_reasonably_met: 'No',
    outcome_approximately_normal: 'Not Applicable',
    small_sample_concern: 'Yes',
    exact_method_needed: 'Yes',
    censoring_present: 'Not Supported',
    latent_construct_interest: 'No',
    dimension_reduction_goal: 'No',
    analysis_scope: 'Unadjusted / Bivariate',
    post_hoc_comparisons_needed: 'No',
  },
  {
    name: "McNemar's Test",
    aliases: ['McNemar Chi-Square Test'],
    goal: ['Compare Groups'],
    variable_relationship_structure: 'DV–IV Directional',
    primary_variable_1_type: 'Binary',
    primary_variable_2_type: 'Binary',
    number_of_dependent_variables: 'One',
    number_of_predictors: 'One',
    number_of_groups_conditions: 'Two',
    sample_relationship: 'Paired / Matched',
    repeated_observations_present: 'Yes',
    number_of_timepoints: 'Two',
    parametric_assumptions_reasonably_met: 'No',
    outcome_approximately_normal: 'Not Applicable',
    censoring_present: 'Not Supported',
    latent_construct_interest: 'No',
    dimension_reduction_goal: 'No',
    analysis_scope: 'Unadjusted / Bivariate',
    post_hoc_comparisons_needed: 'No',
  },
  {
    name: "Cochran's Q Test",
    aliases: [],
    goal: ['Compare Groups'],
    variable_relationship_structure: 'DV–IV Directional',
    primary_variable_1_type: 'Binary',
    primary_variable_2_type: 'Nominal Categorical',
    number_of_dependent_variables: 'One',
    number_of_predictors: 'One',
    number_of_groups_conditions: 'Three or More',
    sample_relationship: 'Repeated Measures',
    repeated_observations_present: 'Yes',
    number_of_timepoints: 'Three or More',
    parametric_assumptions_reasonably_met: 'No',
    outcome_approximately_normal: 'Not Applicable',
    censoring_present: 'Not Supported',
    latent_construct_interest: 'No',
    dimension_reduction_goal: 'No',
    analysis_scope: 'Unadjusted / Bivariate',
    post_hoc_comparisons_needed: 'Yes',
  },
  {
    name: 'Binomial Test',
    aliases: ['Exact Binomial Test'],
    goal: ['Test Frequencies Against Expected Values'],
    primary_variable_1_type: 'Binary',
    primary_variable_2_type: 'None / Not Applicable',
    number_of_dependent_variables: 'One',
    number_of_predictors: 'None / Not Applicable',
    number_of_groups_conditions: 'One',
    sample_relationship: 'None / Not Applicable',
    repeated_observations_present: 'No',
    number_of_timepoints: 'One',
    time_matters_to_analysis: 'No',
    parametric_assumptions_reasonably_met: 'No',
    outcome_approximately_normal: 'Not Applicable',
    exact_method_needed: 'Yes',
    censoring_present: 'Not Supported',
    latent_construct_interest: 'No',
    dimension_reduction_goal: 'No',
    analysis_scope: 'Unadjusted / Bivariate',
  },

  # =======================================================================
  # Regression / Prediction
  # =======================================================================
  {
    name: 'Simple Linear Regression',
    aliases: ['OLS Regression (Simple)', 'Bivariate Regression'],
    goal: ['Predict Outcome'],
    variable_relationship_structure: 'DV–IV Directional',
    primary_variable_1_type: 'Continuous',
    primary_variable_2_type: 'Continuous',
    number_of_dependent_variables: 'One',
    number_of_predictors: 'One',
    repeated_observations_present: 'No',
    number_of_timepoints: 'One',
    time_matters_to_analysis: 'No',
    parametric_assumptions_reasonably_met: 'Yes',
    outcome_approximately_normal: 'Yes',
    censoring_present: 'Not Supported',
    latent_construct_interest: 'No',
    dimension_reduction_goal: 'No',
    analysis_scope: 'Unadjusted / Bivariate',
    primary_output_desired: ['Regression Coefficient'],
  },
  {
    name: 'Multiple Linear Regression',
    aliases: ['OLS Regression', 'Linear Regression'],
    goal: ['Predict Outcome'],
    variable_relationship_structure: 'DV–IV Directional',
    primary_variable_1_type: 'Continuous',
    primary_variable_2_type: 'Mixed',
    number_of_dependent_variables: 'One',
    number_of_predictors: 'Multiple',
    repeated_observations_present: 'No',
    number_of_timepoints: 'One',
    time_matters_to_analysis: 'No',
    covariates_included: 'Supported',
    moderation: 'Supported',
    parametric_assumptions_reasonably_met: 'Yes',
    outcome_approximately_normal: 'Yes',
    censoring_present: 'Not Supported',
    latent_construct_interest: 'No',
    dimension_reduction_goal: 'No',
    analysis_scope: 'Adjusted / Multivariable',
    primary_output_desired: ['Regression Coefficient'],
  },
  {
    name: 'Polynomial Regression',
    aliases: [],
    goal: ['Predict Outcome'],
    variable_relationship_structure: 'DV–IV Directional',
    primary_variable_1_type: 'Continuous',
    primary_variable_2_type: 'Continuous',
    number_of_dependent_variables: 'One',
    number_of_predictors: 'Multiple',
    repeated_observations_present: 'No',
    number_of_timepoints: 'One',
    time_matters_to_analysis: 'No',
    parametric_assumptions_reasonably_met: 'Yes',
    outcome_approximately_normal: 'Yes',
    censoring_present: 'Not Supported',
    latent_construct_interest: 'No',
    dimension_reduction_goal: 'No',
    analysis_scope: 'Adjusted / Multivariable',
    primary_output_desired: ['Regression Coefficient'],
  },
  {
    name: 'Binary Logistic Regression',
    aliases: ['Logistic Regression', 'Logit Regression'],
    goal: ['Predict Outcome', 'Classify Cases'],
    variable_relationship_structure: 'DV–IV Directional',
    primary_variable_1_type: 'Binary',
    primary_variable_2_type: 'Mixed',
    number_of_dependent_variables: 'One',
    number_of_predictors: 'Multiple',
    repeated_observations_present: 'No',
    number_of_timepoints: 'One',
    time_matters_to_analysis: 'No',
    covariates_included: 'Supported',
    moderation: 'Supported',
    outcome_approximately_normal: 'Not Applicable',
    censoring_present: 'Not Supported',
    latent_construct_interest: 'No',
    dimension_reduction_goal: 'No',
    analysis_scope: 'Adjusted / Multivariable',
    primary_output_desired: ['Odds Ratio', 'Regression Coefficient'],
  },
  {
    name: 'Multinomial Logistic Regression',
    aliases: ['Multinomial Logit'],
    goal: ['Predict Outcome', 'Classify Cases'],
    variable_relationship_structure: 'DV–IV Directional',
    primary_variable_1_type: 'Nominal Categorical',
    primary_variable_2_type: 'Mixed',
    number_of_dependent_variables: 'One',
    number_of_predictors: 'Multiple',
    repeated_observations_present: 'No',
    number_of_timepoints: 'One',
    time_matters_to_analysis: 'No',
    covariates_included: 'Supported',
    moderation: 'Supported',
    outcome_approximately_normal: 'Not Applicable',
    censoring_present: 'Not Supported',
    latent_construct_interest: 'No',
    dimension_reduction_goal: 'No',
    analysis_scope: 'Adjusted / Multivariable',
    primary_output_desired: ['Odds Ratio', 'Regression Coefficient'],
  },
  {
    name: 'Ordinal Logistic Regression',
    aliases: ['Proportional Odds Model', 'Ordered Logit'],
    goal: ['Predict Outcome'],
    variable_relationship_structure: 'DV–IV Directional',
    primary_variable_1_type: 'Ordinal',
    primary_variable_2_type: 'Mixed',
    number_of_dependent_variables: 'One',
    number_of_predictors: 'Multiple',
    repeated_observations_present: 'No',
    number_of_timepoints: 'One',
    time_matters_to_analysis: 'No',
    covariates_included: 'Supported',
    moderation: 'Supported',
    outcome_approximately_normal: 'Not Applicable',
    censoring_present: 'Not Supported',
    latent_construct_interest: 'No',
    dimension_reduction_goal: 'No',
    analysis_scope: 'Adjusted / Multivariable',
    primary_output_desired: ['Odds Ratio', 'Regression Coefficient'],
  },
  {
    name: 'Poisson Regression',
    aliases: [],
    goal: ['Predict Outcome'],
    variable_relationship_structure: 'DV–IV Directional',
    primary_variable_1_type: 'Count',
    primary_variable_2_type: 'Mixed',
    number_of_dependent_variables: 'One',
    number_of_predictors: 'Multiple',
    repeated_observations_present: 'No',
    number_of_timepoints: 'One',
    time_matters_to_analysis: 'No',
    covariates_included: 'Supported',
    moderation: 'Supported',
    outcome_approximately_normal: 'Not Applicable',
    overdispersion_present: 'No',
    many_zero_values: 'No',
    censoring_present: 'Not Supported',
    latent_construct_interest: 'No',
    dimension_reduction_goal: 'No',
    analysis_scope: 'Adjusted / Multivariable',
    primary_output_desired: ['Regression Coefficient'],
  },
  {
    name: 'Negative Binomial Regression',
    aliases: ['NegBin Regression'],
    goal: ['Predict Outcome'],
    variable_relationship_structure: 'DV–IV Directional',
    primary_variable_1_type: 'Count',
    primary_variable_2_type: 'Mixed',
    number_of_dependent_variables: 'One',
    number_of_predictors: 'Multiple',
    repeated_observations_present: 'No',
    number_of_timepoints: 'One',
    time_matters_to_analysis: 'No',
    covariates_included: 'Supported',
    moderation: 'Supported',
    outcome_approximately_normal: 'Not Applicable',
    overdispersion_present: 'Yes',
    many_zero_values: 'No',
    censoring_present: 'Not Supported',
    latent_construct_interest: 'No',
    dimension_reduction_goal: 'No',
    analysis_scope: 'Adjusted / Multivariable',
    primary_output_desired: ['Regression Coefficient'],
  },
  {
    name: 'Zero-Inflated Poisson Regression',
    aliases: ['ZIP Regression'],
    goal: ['Predict Outcome'],
    variable_relationship_structure: 'DV–IV Directional',
    primary_variable_1_type: 'Count',
    primary_variable_2_type: 'Mixed',
    number_of_dependent_variables: 'One',
    number_of_predictors: 'Multiple',
    repeated_observations_present: 'No',
    number_of_timepoints: 'One',
    time_matters_to_analysis: 'No',
    covariates_included: 'Supported',
    outcome_approximately_normal: 'Not Applicable',
    overdispersion_present: 'No',
    many_zero_values: 'Yes',
    censoring_present: 'Not Supported',
    latent_construct_interest: 'No',
    dimension_reduction_goal: 'No',
    analysis_scope: 'Adjusted / Multivariable',
    primary_output_desired: ['Regression Coefficient'],
  },
  {
    name: 'Zero-Inflated Negative Binomial Regression',
    aliases: ['ZINB Regression'],
    goal: ['Predict Outcome'],
    variable_relationship_structure: 'DV–IV Directional',
    primary_variable_1_type: 'Count',
    primary_variable_2_type: 'Mixed',
    number_of_dependent_variables: 'One',
    number_of_predictors: 'Multiple',
    repeated_observations_present: 'No',
    number_of_timepoints: 'One',
    time_matters_to_analysis: 'No',
    covariates_included: 'Supported',
    outcome_approximately_normal: 'Not Applicable',
    overdispersion_present: 'Yes',
    many_zero_values: 'Yes',
    censoring_present: 'Not Supported',
    latent_construct_interest: 'No',
    dimension_reduction_goal: 'No',
    analysis_scope: 'Adjusted / Multivariable',
    primary_output_desired: ['Regression Coefficient'],
  },
  {
    name: 'Probit Regression',
    aliases: ['Probit Model'],
    goal: ['Predict Outcome', 'Classify Cases'],
    variable_relationship_structure: 'DV–IV Directional',
    primary_variable_1_type: 'Binary',
    primary_variable_2_type: 'Mixed',
    number_of_dependent_variables: 'One',
    number_of_predictors: 'Multiple',
    repeated_observations_present: 'No',
    number_of_timepoints: 'One',
    time_matters_to_analysis: 'No',
    covariates_included: 'Supported',
    moderation: 'Supported',
    outcome_approximately_normal: 'Not Applicable',
    censoring_present: 'Not Supported',
    latent_construct_interest: 'No',
    dimension_reduction_goal: 'No',
    analysis_scope: 'Adjusted / Multivariable',
    primary_output_desired: ['Regression Coefficient'],
  },

  # =======================================================================
  # Mediation / Moderation / Path
  # =======================================================================
  {
    name: 'Mediation Analysis (Regression-Based)',
    aliases: ['Baron–Kenny Mediation'],
    goal: ['Test Mediation'],
    variable_relationship_structure: 'DV–IV Directional',
    primary_variable_1_type: 'Continuous',
    primary_variable_2_type: 'Mixed',
    number_of_dependent_variables: 'One',
    number_of_predictors: 'Multiple',
    repeated_observations_present: 'No',
    number_of_timepoints: 'One',
    time_matters_to_analysis: 'No',
    mediation: 'Required',
    covariates_included: 'Supported',
    censoring_present: 'Not Supported',
    latent_construct_interest: 'No',
    dimension_reduction_goal: 'No',
    analysis_scope: 'Adjusted / Multivariable',
    primary_output_desired: ['Regression Coefficient'],
  },
  {
    name: 'Moderation Analysis (Interaction Regression)',
    aliases: ['Interaction Analysis'],
    goal: ['Test Moderation'],
    variable_relationship_structure: 'DV–IV Directional',
    primary_variable_1_type: 'Continuous',
    primary_variable_2_type: 'Mixed',
    number_of_dependent_variables: 'One',
    number_of_predictors: 'Multiple',
    repeated_observations_present: 'No',
    number_of_timepoints: 'One',
    time_matters_to_analysis: 'No',
    moderation: 'Required',
    covariates_included: 'Supported',
    censoring_present: 'Not Supported',
    latent_construct_interest: 'No',
    dimension_reduction_goal: 'No',
    analysis_scope: 'Adjusted / Multivariable',
    primary_output_desired: ['Regression Coefficient'],
  },
  {
    name: 'Moderated Mediation Analysis',
    aliases: ['Conditional Indirect Effects'],
    goal: ['Test Mediation', 'Test Moderation'],
    variable_relationship_structure: 'DV–IV Directional',
    primary_variable_1_type: 'Continuous',
    primary_variable_2_type: 'Mixed',
    number_of_dependent_variables: 'One',
    number_of_predictors: 'Multiple',
    repeated_observations_present: 'No',
    number_of_timepoints: 'One',
    time_matters_to_analysis: 'No',
    mediation: 'Required',
    moderation: 'Required',
    covariates_included: 'Supported',
    censoring_present: 'Not Supported',
    latent_construct_interest: 'No',
    dimension_reduction_goal: 'No',
    analysis_scope: 'Adjusted / Multivariable',
    primary_output_desired: ['Regression Coefficient'],
  },
  {
    name: 'Path Analysis',
    aliases: [],
    goal: ['Predict Outcome', 'Test Mediation'],
    variable_relationship_structure: 'DV–IV Directional',
    primary_variable_1_type: 'Continuous',
    primary_variable_2_type: 'Mixed',
    number_of_dependent_variables: 'Multiple',
    number_of_predictors: 'Multiple',
    repeated_observations_present: 'No',
    number_of_timepoints: 'One',
    time_matters_to_analysis: 'No',
    mediation: 'Supported',
    covariates_included: 'Supported',
    latent_construct_interest: 'No',
    censoring_present: 'Not Supported',
    dimension_reduction_goal: 'No',
    analysis_scope: 'Multivariate',
    primary_output_desired: ['Regression Coefficient', 'Fit Statistic'],
  },
  {
    name: 'Structural Equation Modeling (SEM)',
    aliases: ['SEM'],
    goal: ['Identify Latent Structure', 'Test Mediation', 'Predict Outcome'],
    variable_relationship_structure: 'DV–IV Directional',
    primary_variable_1_type: 'Continuous',
    primary_variable_2_type: 'Mixed',
    number_of_dependent_variables: 'Multiple',
    number_of_predictors: 'Multiple',
    repeated_observations_present: 'No',
    number_of_timepoints: 'One',
    time_matters_to_analysis: 'No',
    mediation: 'Supported',
    covariates_included: 'Supported',
    latent_construct_interest: 'Yes',
    censoring_present: 'Not Supported',
    dimension_reduction_goal: 'No',
    analysis_scope: 'Multivariate',
    primary_output_desired: ['Latent Factors', 'Regression Coefficient', 'Fit Statistic'],
  },

  # =======================================================================
  # Longitudinal / Multilevel
  # =======================================================================
  {
    name: 'Linear Mixed-Effects Model',
    aliases: ['LMM', 'Multilevel Linear Model', 'Hierarchical Linear Model', 'HLM'],
    goal: ['Predict Outcome'],
    variable_relationship_structure: 'DV–IV Directional',
    primary_variable_1_type: 'Continuous',
    primary_variable_2_type: 'Mixed',
    number_of_dependent_variables: 'One',
    number_of_predictors: 'Multiple',
    repeated_observations_present: 'Yes',
    nested_or_clustered_data: 'Required',
    data_hierarchy: 'Nested / Multilevel',
    covariates_included: 'Supported',
    moderation: 'Supported',
    parametric_assumptions_reasonably_met: 'Yes',
    outcome_approximately_normal: 'Yes',
    censoring_present: 'Not Supported',
    latent_construct_interest: 'No',
    dimension_reduction_goal: 'No',
    analysis_scope: 'Adjusted / Multivariable',
    primary_output_desired: ['Regression Coefficient'],
  },
  {
    name: 'Generalized Linear Mixed Model (GLMM)',
    aliases: ['GLMM'],
    goal: ['Predict Outcome'],
    variable_relationship_structure: 'DV–IV Directional',
    primary_variable_2_type: 'Mixed',
    number_of_dependent_variables: 'One',
    number_of_predictors: 'Multiple',
    repeated_observations_present: 'Yes',
    nested_or_clustered_data: 'Required',
    data_hierarchy: 'Nested / Multilevel',
    covariates_included: 'Supported',
    moderation: 'Supported',
    censoring_present: 'Not Supported',
    latent_construct_interest: 'No',
    dimension_reduction_goal: 'No',
    analysis_scope: 'Adjusted / Multivariable',
    primary_output_desired: ['Regression Coefficient'],
  },
  {
    name: 'Generalized Estimating Equations (GEE)',
    aliases: ['GEE'],
    goal: ['Predict Outcome'],
    variable_relationship_structure: 'DV–IV Directional',
    primary_variable_2_type: 'Mixed',
    number_of_dependent_variables: 'One',
    number_of_predictors: 'Multiple',
    repeated_observations_present: 'Yes',
    nested_or_clustered_data: 'Required',
    covariates_included: 'Supported',
    censoring_present: 'Not Supported',
    latent_construct_interest: 'No',
    dimension_reduction_goal: 'No',
    analysis_scope: 'Adjusted / Multivariable',
    primary_output_desired: ['Regression Coefficient'],
  },
  {
    name: 'Growth Curve Modeling',
    aliases: ['Growth Curve Analysis', 'Trajectory Analysis'],
    goal: ['Model Change Over Time'],
    variable_relationship_structure: 'DV–IV Directional',
    primary_variable_1_type: 'Continuous',
    primary_variable_2_type: 'Mixed',
    number_of_dependent_variables: 'One',
    number_of_predictors: 'Multiple',
    repeated_observations_present: 'Yes',
    number_of_timepoints: 'Three or More',
    time_matters_to_analysis: 'Yes',
    nested_or_clustered_data: 'Required',
    data_hierarchy: 'Longitudinal',
    covariates_included: 'Supported',
    censoring_present: 'Not Supported',
    latent_construct_interest: 'No',
    dimension_reduction_goal: 'No',
    analysis_scope: 'Adjusted / Multivariable',
    primary_output_desired: ['Regression Coefficient'],
  },
  {
    name: 'Latent Growth Curve Modeling',
    aliases: ['LGCM', 'Latent Growth Modeling'],
    goal: ['Model Change Over Time', 'Identify Latent Structure'],
    variable_relationship_structure: 'DV–IV Directional',
    primary_variable_1_type: 'Continuous',
    primary_variable_2_type: 'Mixed',
    number_of_dependent_variables: 'One',
    number_of_predictors: 'Multiple',
    repeated_observations_present: 'Yes',
    number_of_timepoints: 'Three or More',
    time_matters_to_analysis: 'Yes',
    nested_or_clustered_data: 'Required',
    data_hierarchy: 'Longitudinal',
    latent_construct_interest: 'Yes',
    covariates_included: 'Supported',
    censoring_present: 'Not Supported',
    dimension_reduction_goal: 'No',
    analysis_scope: 'Multivariate',
    primary_output_desired: ['Latent Factors', 'Regression Coefficient', 'Fit Statistic'],
  },

  # =======================================================================
  # Survival / Time-to-Event
  # =======================================================================
  {
    name: 'Log-Rank Test',
    aliases: ['Mantel–Cox Test'],
    goal: ['Compare Groups', 'Analyze Survival / Time-to-Event'],
    variable_relationship_structure: 'DV–IV Directional',
    primary_variable_1_type: 'Time-to-Event',
    primary_variable_2_type: 'Nominal Categorical',
    number_of_dependent_variables: 'One',
    number_of_predictors: 'One',
    sample_relationship: 'Independent',
    repeated_observations_present: 'No',
    number_of_timepoints: 'Continuous / Event-Based',
    time_matters_to_analysis: 'Yes',
    parametric_assumptions_reasonably_met: 'No',
    censoring_present: 'Required',
    latent_construct_interest: 'No',
    dimension_reduction_goal: 'No',
    analysis_scope: 'Unadjusted / Bivariate',
    primary_output_desired: ['Group Difference'],
  },
  {
    name: 'Cox Proportional Hazards Regression',
    aliases: ['Cox Regression', 'Proportional Hazards Model', 'Cox PH'],
    goal: ['Predict Outcome', 'Analyze Survival / Time-to-Event'],
    variable_relationship_structure: 'DV–IV Directional',
    primary_variable_1_type: 'Time-to-Event',
    primary_variable_2_type: 'Mixed',
    number_of_dependent_variables: 'One',
    number_of_predictors: 'Multiple',
    repeated_observations_present: 'No',
    number_of_timepoints: 'Continuous / Event-Based',
    time_matters_to_analysis: 'Yes',
    censoring_present: 'Required',
    covariates_included: 'Supported',
    moderation: 'Supported',
    latent_construct_interest: 'No',
    dimension_reduction_goal: 'No',
    analysis_scope: 'Adjusted / Multivariable',
    primary_output_desired: ['Hazard Ratio', 'Regression Coefficient'],
  },
  {
    name: 'Parametric Survival Regression',
    aliases: ['Accelerated Failure Time Model', 'AFT Model'],
    goal: ['Predict Outcome', 'Analyze Survival / Time-to-Event'],
    variable_relationship_structure: 'DV–IV Directional',
    primary_variable_1_type: 'Time-to-Event',
    primary_variable_2_type: 'Mixed',
    number_of_dependent_variables: 'One',
    number_of_predictors: 'Multiple',
    repeated_observations_present: 'No',
    number_of_timepoints: 'Continuous / Event-Based',
    time_matters_to_analysis: 'Yes',
    censoring_present: 'Required',
    covariates_included: 'Supported',
    moderation: 'Supported',
    parametric_assumptions_reasonably_met: 'Yes',
    latent_construct_interest: 'No',
    dimension_reduction_goal: 'No',
    analysis_scope: 'Adjusted / Multivariable',
    primary_output_desired: ['Hazard Ratio', 'Regression Coefficient'],
  },
].freeze

created_count = 0
existing_count = 0

STATISTICAL_TESTS_SEED.each_with_index do |attrs, i|
  attrs = attrs.merge(position: i + 1)
  test = StatisticalTest.find_by(name: attrs[:name])
  if test
    existing_count += 1
  else
    StatisticalTest.create!(attrs)
    created_count += 1
  end
end

puts "Seeded statistical tests: created #{created_count}, already existed #{existing_count}, total in catalog #{StatisticalTest.count}"
