
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: tdl_2025_development
  username: postgres
  password: postgres
  host: localhost
  port: 5432

test:
  <<: *default
  database: tdl_2025_test
  username: postgres
  password: postgres
  host: localhost
  port: 5432

production:
  <<: *default
  database: tdl_2025_production
  username: tdl_2025
  password: <%= ENV["TDL_2025_DATABASE_PASSWORD"] %>
